### ISSUE TITLE
global: beta version checklist

### ISSUE THREAD

**Issue by krzysztof** [inveniosoftware/invenio-admin#38]
## 1. Global API overview + Prepare docs structure:
- [x] 1.1 Synchronize with new documentation structure inveniosoftware/cookiecutter-invenio-module#56
  - [x] ``docs/requirements.txt`` should exist ([EXAMPLE](https://github.com/inveniosoftware/invenio-celery/blob/master/docs/requirements.txt))
  - [x] Diff files from the module vs cookiecutter module on:
    - CONTRIBUTING.rst, LICENSE, README.rst, .dockerignore,, .gitignore, run-tests.sh, pytest.ini
- [x] 1.2 API proof-reading
  - [x] Read and understand API
  - [x] Check existing API methods for feature completeness and correctness. Add missing API if necessary.
## 2. Local code improvements:
- [x] 2.1 General code improvements 
  - [x] Check code quality all over the module
  - [x] Does QualifiedCode report any errors that can be fixed?
  - [x] Is the test coverage % sufficient across the whole module?
  - [x] Is all core code (API, models) covered with unit test?
  - [x] grep the module for "TODO"/"FIXME". Remove where no longer relevant.
  - [x] Are all strings decorated as translation strings?
- [x] 2.2 Dependencies:
  - [x] Remove unused dependencies in ``setup.py`` and ``requirements-devel.txt``
  - [x] Module should not depend on ``flask_cli`` nor should it instantiate ``FlaskCLI`` extension.
- [x] 2.3 Example app should run.
### 3.1. Write
- [x] 3.1.1 General documentation: 
  - [x] Document usage / getting started guide inside package docstring ([EXAMPLE](https://github.com/inveniosoftware/invenio-db/blob/master/invenio_db/__init__.py))
  - [x] Make config variables self-documented and imported in the package docs under 'Configuration' section ([EXAMPLE](https://invenio-celery.readthedocs.io/en/latest/usage.html#module-invenio_celery.config) and [EXAMPLE](https://github.com/inveniosoftware/invenio-celery/blob/master/invenio_celery/__init__.py#L25-L35))
  - [x] Add docstring documentation for example app
  - [x] Are all API methods, classes and modules plugged in the documentation as autodoc?
  - [x] Add intersphinx mappings where convenient and make sure they work compiled documentation ([EXAMPLE_REFERENCE](https://github.com/inveniosoftware/invenio-admin/blob/master/invenio_admin/ext.py#L119) and [EXAMPLE_CONFIG](https://github.com/inveniosoftware/invenio-admin/blob/master/docs/conf.py#L332-L337))
  - [x] Are all chapter/section underlines (e.g. ``====``, ``-----``) matching the length of the section/chapter title?
- [x] 3.1.2 Functional documentation:
  - [x] Document all public method docstrings with description and types
    - [x] Methods and functions that accept ``**kwargs`` should document potential arguments and mention if they are passed to another function/method which provides documentation for them.
  - [x] Document signals
### 3.2 Review (read the compiled documentation A-Z)
- [x] Is all imported autodoc documentation being loaded correctly?
- [x] Do all pages and sections contain some text?
- [x] Are all links on the page (API class references, intersphinx links) resolvable?
- [x] Are all text and characters rendered correctly?
  - Non-breaking newlines going outside the page?
  - Strange characters, half-escaped style markers inside docstrings (*, **, ``)
- [x] Docs are compiled and assembled from multiple file/package docstings into single pages - is the assembled block of text easy to read? Unify the compiled text if possible.
- [x] Create a new virtual environment and follow the installation and then getting started guide - does it actually work as described? Add and improve documentation if the description is missing something.
## 4. Miscellaneous: 
- [x] isort glob fixes:
  - [x] isort in ``run-tests.sh`` should look as follows: ``isort -rc -c -df`` ([EXAMPLE](https://github.com/inveniosoftware/invenio-deposit/blob/master/run-tests.sh#L28))
  - [x] ``.editorconfig`` should specify ``skip=.eggs`` ([EXAMPLE](https://github.com/inveniosoftware/invenio-deposit/blob/1f112b67a4bdef0c810ece362ddc1af0184a9d94/.editorconfig#L42))
- [x] pydocstyle should check: ``pydocstyle invenio-foobar tests docs`` ([EXAMPLE](https://github.com/inveniosoftware/invenio-deposit/blob/master/run-tests.sh#L27))
- [x] ``MANIFEST.txt``
  - [x] Should be sorted and without comments.
  - [x] Should **NOT** contain ``include *.py``
- [x] ``.editorconfig:known_third_party`` should match 1-to-1 all devel requirements in ``requirements-devel.txt`` (should also be sorted) ([.editorconfig](https://github.com/inveniosoftware/invenio-communities/blob/master/.editorconfig#L40) and [requirements-devel.txt](https://github.com/inveniosoftware/invenio-communities/blob/master/requirements-devel.txt))
- [x] ``CONTRIBUTING.rst``:
  - Change `invenio` to `Invenio-Foobar` ([SEE](https://github.com/inveniosoftware/invenio-admin/blame/master/CONTRIBUTING.rst#L56-L58))
- [x] ``setup.py``:
  - [x] keywords: check existing keywords for relevance / add new ones
  - [x] entrypoints: check if correct
  - [x] Apply ``'Development Status :: 4 - Beta'``
- Change double bracket "string" to 'string' if you spot it anywhere.

**Comment by krzysztof** [comment]
Each root bullet-point can be a single commit unless split into several.

**Comment by krzysztof** [comment]
## 5. Invenio-Admin extra
### Custom pages
- [ ] Add custom admin views
- [ ] Extend the documentation with custom admin views creation

**Comment by krzysztof** [comment]
@lnielsen In example app, why is the whole admin not protected by the permission, except the single model view that you register: https://github.com/inveniosoftware/invenio-admin/blob/feature-beta/examples/app.py ?

**Comment by lnielsen** [comment]
@krzysztof Not sure. Authentication was removed in ab55d697722656e8d9f6873c6494e4aad7c36039, but seems like we could add it back in to have it available in the example app.

**Comment by krzysztof** [comment]
Then it would also need some demo user.

In addition to that, should demo app be unified with the user's guide tutorial?

**Comment by lnielsen** [comment]
> Then it would also need some demo user.

Yep, like in https://github.com/inveniosoftware/invenio-admin/commit/ab55d697722656e8d9f6873c6494e4aad7c36039#diff-86d2f29b7151f1dfb6b158f5f495ba35R54

> In addition to that, should demo app be unified with the user's guide tutorial?

I would not unify them as they serve different purposes. User guide, is an overview for developers how to use the module (focused on communication of the module features and concepts). Example app is focused on having a minimal Flask application which you can use when developing the module and to see everything running in one go.

**Comment by slint** [comment]
@lnielsen FYI for the example app's `app-fixtures.sh` already [creates a user](https://github.com/inveniosoftware/invenio-admin/blob/feature-beta/examples/app-fixtures.sh#L15). The issue here is that there is no "login" button or forced redirection to the login view, since the user never has to access a protected view as part of the guide (`/admin` is unprotected, [only the additional ModelView is protected](https://github.com/inveniosoftware/invenio-admin/blob/feature-beta/examples/app.py#L116)).

I think the whole `/admin` endpoint should be protected using the proper configuration, which is also the common use-case.
